image: Visual Studio 2017

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- dotnet restore
- dotnet build VulkanCore.sln

test: off
